INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drinks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Mobile', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Series', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Small Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('School Items', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Babies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Apparel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Camping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Travel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Health', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cleaning', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Food', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Office', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Outdoors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Decoration', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Party', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('School Items', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Babies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Apparel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drinks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Mobile', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Series', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Small Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('School Items', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Babies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Apparel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
